UPDATE cruises
    SET cruise_name = 'Bahamas',
            START_DATE = '01-DEC-11'
    WHERE CRUISE_ID = 1;
    
INSERT INTO EMP_COMPENSATION (EMPLOYEE_ID,SALARY,LAST_CHANGED_DATE)
VALUES                      (1,60000,SYSDATE);

UPDATE EMP_COMPENSATION
    SET SALARY = SALARY * 1.03,
        LAST_CHANGED_DATE = SYSDATE
        WHERE EMPLOYEE_ID = 1;

CREATE SEQUENCE SEQ_EMPLOYEE_ID;

INSERT INTO EMPLOYEES (EMPLOYEE_ID,SHIP_ID,FIRST_NAME,LAST_NAME)
VALUES                      (SEQ_EMPLOYEE_ID.NEXTVAL,1,'Christian','Batista');

CREATE TABLE PROJECTS
(   PROJECT_ID      NUMBER CONSTRAINT PROJECT_ID_PK PRIMARY KEY
,   PROJECT_NAME    VARCHAR2 (40)
,   COST            NUMBER
,   CONSTRAINT      CK_COST CHECK (COST < 1000000));

INSERT INTO PROJECTS    (PROJECT_ID, PROJECT_NAME, COST)
VALUES                  (1, 'Hull Cleaning', 340000);
INSERT INTO PROJECTS    (PROJECT_ID, PROJECT_NAME, COST)
VALUES                  (2, 'DECK Resurfacing', 964000);
INSERT INTO PROJECTS    (PROJECT_ID, PROJECT_NAME, COST)
VALUES                  (3, 'Lifeboat Inspection', 12000);

UPDATE PROJECTS
    SET COST = COST * 1.20;
SELECT * FROM PROJECTS;

UPDATE PROJECTS
    SET COST = COST * 1.20
WHERE COST * 1.20 <1000000;

CREATE SEQUENCE SEQ_CONSTRUCTION_ID;

CREATE TABLE PROJECTS_LISTING
(   CONSTRUCTION_ID      NUMBER CONSTRAINT CONSTRUCTION_ID_PK PRIMARY KEY
,   PROJECT_NAME        VARCHAR2 (40)
,   PROJECT_MANAGER_ID  NUMBER
);
ALTER TABLE PROJECTS_LISTING
    ADD CONSTRAINT PROJECT_MANAGER_ID_FK FOREIGN KEY (PROJECT_MANAGER_ID)
                REFERENCES POSITIONS (POSITION_ID);
                
INSERT INTO POSITIONS 
VALUES (1,'Project Manager','Y');
    
INSERT INTO projects_listing
VALUES (SEQ_CONSTRUCTION_ID.NEXTVAL, 'CLEARING LOT 1', 1);



