CREATE TABLE PROJECTS
(  PROJECT_ID   NUMBER PRIMARY KEY,
   PROJECT_NAME VARCHAR2(40),
   COST         NUMBER,
   CONSTRAINT CK_COST CHECK (COST < 1000000));
   
INSERT INTO PROJECTS    (PROJECT_ID, PROJECT_NAME, COST)
VALUES                  (1, 'HULL CLEANING', 340000);

INSERT INTO PROJECTS    (PROJECT_ID, PROJECT_NAME, COST)
VALUES                  (2,'Deck Resurfacing', 964000);

INSERT INTO PROJECTS    (PROJECT_ID, PROJECT_NAME, COST)
VALUES                  (3,'Lifeboat Inspection', 12000);